services:
  app:
    build: .
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: on-failure
