services:
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
      MYSQL_PASSWORD: studentpwd
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "3306:3306"
    volumes:
      - student_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  student_mysql_data: